export const FETCH_USER = "FETCH_USER";
export const SUBMITING_SURVEY = "SUBMITING_SURVEY";
export const SUBMITED_SURVEY = "SUBMITED_SURVEY";
export const FETCHING_SURVEYS = "FETCHING_SURVEYS";
export const FETCHED_SURVEYS = "FETCHED_SURVEYS";